"""resolving schema 

Revision ID: f63ef91c62e5
Revises: 1d271ecd622c
Create Date: 2025-07-03 14:23:50.215915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f63ef91c62e5'
down_revision = '1d271ecd622c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guests')
    op.drop_table('episodes')
    op.drop_table('appearances')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appearances',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('rating', sa.FLOAT(), nullable=False),
    sa.Column('episode_id', sa.INTEGER(), nullable=True),
    sa.Column('guest_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], name=op.f('fk_appearances_episode_id_episodes')),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], name=op.f('fk_appearances_guest_id_guests')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appearances'))
    )
    op.create_table('episodes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('number', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_episodes'))
    )
    op.create_table('guests',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('occupation', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guests'))
    )
    # ### end Alembic commands ###
